// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	OrderID        int32        `json:"order_id"`
	CustomerID     int32        `json:"customer_id"`
	ServiceID      int32        `json:"service_id"`
	OrderStatus    string       `json:"order_status"`
	OrderStarted   time.Time    `json:"order_started"`
	OrderDelivered sql.NullTime `json:"order_delivered"`
}

type Service struct {
	ServiceID    int32  `json:"service_id"`
	ServiceName  string `json:"service_name"`
	ServicePrice int64  `json:"service_price"`
}

type User struct {
	// this will consist of unique user_id
	UserID            int32     `json:"user_id"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	Phone             string    `json:"phone"`
	Address           string    `json:"address"`
	TotalOrders       int32     `json:"total_orders"`
	HashedPassword    string    `json:"hashed_password"`
	CreatedAt         time.Time `json:"created_at"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
}
