// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID                int32     `json:"id"`
	OrderID           int64     `json:"order_id"`
	UserID            int32     `json:"user_id"`
	ServiceIds        int32     `json:"service_ids"`
	OrderStatus       string    `json:"order_status"`
	OrderStarted      time.Time `json:"order_started"`
	OrderDelivered    bool      `json:"order_delivered"`
	OrderDeliveryTime time.Time `json:"order_delivery_time"`
}

type Service struct {
	ServiceID    int32  `json:"service_id"`
	ServiceName  string `json:"service_name"`
	ServicePrice int64  `json:"service_price"`
	ServiceImage string `json:"service_image"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	CleintIp     string    `json:"cleint_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	// this will consist of unique user_id
	UserID            int32     `json:"user_id"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	Phone             string    `json:"phone"`
	Address           string    `json:"address"`
	TotalOrders       int32     `json:"total_orders"`
	HashedPassword    string    `json:"hashed_password"`
	CreatedAt         time.Time `json:"created_at"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
}
