basePath: /api/v1
definitions:
  api.userResponse:
    properties:
      address:
        type: string
      created_at:
        type: string
      email:
        type: string
      name:
        type: string
      password_changed_at:
        type: string
      phone:
        type: string
      total_orders:
        type: integer
      user_id:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: This is a backend API for CTT_Back the Applicaation with integrated
    CRM + Ordering System.
  termsOfService: http://swagger.io/terms/
  title: Cnx-Backend API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: create user by giving all the user info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.userResponse'
      summary: Create a User
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
